# Shell variables
# Generated by 'wal'
wallpaper='/home/brunorbsf/MiscProjects/dotfiles/astronaut.jpg'

# Special
background='#0F161E'
foreground='#86e3c2'
cursor='#86e3c2'

# Colors
color0='#0F161E'
color1='#32504E'
color2='#595A58'
color3='#BC4F4F'
color4='#28AC56'
color5='#B8A73A'
color6='#953D9E'
color7='#86e3c2'
color8='#5d9e87'
color9='#32504E'
color10='#595A58'
color11='#BC4F4F'
color12='#28AC56'
color13='#B8A73A'
color14='#953D9E'
color15='#86e3c2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
