--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/brunorbsf/MiscProjects/dotfiles/astronaut.jpg"

-- Special
background="#0F161E"
foreground="#86e3c2"
cursor="#86e3c2"

-- Colors
color0="#0F161E"
color1="#32504E"
color2="#595A58"
color3="#BC4F4F"
color4="#28AC56"
color5="#B8A73A"
color6="#953D9E"
color7="#86e3c2"
color8="#5d9e87"
color9="#32504E"
color10="#595A58"
color11="#BC4F4F"
color12="#28AC56"
color13="#B8A73A"
color14="#953D9E"
color15="#86e3c2"
